model:
  module: em3dfold.models.v2.model_refresh
  class_name: Model
  args:
    n_block: 12
    use_checkpoint: false
    d_node: 256
    d_edge: 128
    d_head: 48
    n_qk_point: 4
    n_v_point: 8
    n_head: 8
    k: 32
    c_grid: 1
    pred_node_exist: false
    pred_edge_exist: true
    pred_pairing: false
    use_seq_attn: true
    seq_attn_every: 2
    geometry_update_every: 4
