model:
  module: em3dfold.models.v3x2_na_ss.model
  class_name: Model
  args:
    n_block: 12
    use_checkpoint: false
    d_node: 256
    d_edge: 128
    d_head: 48
    n_qk_point: 4
    n_v_point: 8
    n_head: 8
    k: 32
    c_grid: 1
    d_cryo_emb: 256
    cube_size: 23
    rectangle_length: 15
    pred_node_exist: false
    pred_edge_exist: true
    pred_pairing: true
    pred_ss: true
    pred_na_type: true
    use_predicted_pairing_feedback: true
    use_seq_attn: true
    seq_attn_every: 2
    geometry_update_every: 4
    recycle_use_full_structure: true
    cube_scunet_head_dim: 16
    cube_scunet_window_size: 3
    cube_scunet_drop_path: 0.0
    cube_scunet_trans_ratio: 0.25
    cube_scunet_max_trans_dim: 128
